# Site settings
title: Yasmic
email: yami.cm88@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Automotive open system architecture(AUTOSAR) is the standardasied architecture developed by some of the leading automotive companies for developing automotive softwares for ECUs.
  Autosar has developed in order to abolish the application software component dependancy with the underlying hardware, so that the 
  application can be indipendantly developed without worrying about the poratability to any hardware.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
